<a href="https://colab.research.google.com/github/DeathstrokeAJ/Python-Practical-/blob/main/Exp11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.10.12


In [ ]:
import numpy as np

In [ ]:
height = [4.4, 5.6]

In [ ]:
np_height = np.array(height)

In [ ]:
weight = [5.6,4.4]

In [ ]:
np_weight = np.array(weight)

In [ ]:
bmi = np_weight/np_height**2

In [ ]:
bmi


array([0.2892562 , 0.14030612])

In [ ]:
np.array([4.5,"er",True])

array(['4.5', 'er', 'True'], dtype='<U32')

In [ ]:
weight + height

[54.54, 85.6, 57.8, 49.8, 4.4, 5.6, 7.8, 9.8]

In [ ]:
np_weight + np_height

array([58.94, 91.2 , 65.6 , 59.6 ])

In [ ]:
bmi

array([2.81714876, 2.72959184, 0.95003287, 0.51853394])

In [ ]:
bmi[1]

2.729591836734694

In [ ]:
bmi> 76

array([False, False, False, False])

In [ ]:
bmi[bmi>1]

array([2.81714876, 2.72959184])

In [ ]:
baseball = [4,6,6,8,9]

In [ ]:
np_baseball = np.array(baseball)

In [ ]:
type(np_baseball)

numpy.ndarray

In [ ]:
height = [7.8, 4.6,8.6,8.9]

In [ ]:
np_height = np.array(height)

In [ ]:
np_height_m = np_height * 0.0254
print(np_height_m)

[0.19812 0.11684 0.21844 0.22606]


In [ ]:
np_weight_kg = np_weight*0.0453592
bmi = np_weight_kg/np_height_m**2
bmi

array([ 63.02660025, 284.41732952,  54.94508999,  44.20254577])

In [ ]:
light = bmi<60
bmi
print(light)
bmi[bmi<60]

[False False  True  True]


array([54.94508999, 44.20254577])